
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorUsuario;

/** CUP generated class containing symbol constants. */
public class parserUSym {
  /* terminals */
  public static final int Formulario = 52;
  public static final int EliminarUsuario = 27;
  public static final int NuevoFormulario = 32;
  public static final int Opciones = 72;
  public static final int Exclamation = 4;
  public static final int EliminarForm = 39;
  public static final int Coma = 17;
  public static final int Usuario = 21;
  public static final int Comilla = 18;
  public static final int Parentesis_R = 10;
  public static final int IniSolicitud = 7;
  public static final int Llave_R = 14;
  public static final int FinSolicitud = 8;
  public static final int Parentesis_L = 9;
  public static final int Imagen = 59;
  public static final int TituloForm = 34;
  public static final int Llave_L = 13;
  public static final int Estructura = 78;
  public static final int TemaForm = 36;
  public static final int FechaF = 30;
  public static final int ParametrosComponente = 47;
  public static final int Corchete_R = 12;
  public static final int DosP = 16;
  public static final int Corchete_L = 11;
  public static final int InicioGuardaForm = 76;
  public static final int CrearUsuario = 20;
  public static final int Boton = 61;
  public static final int ParametroForm = 31;
  public static final int FinSolicitudes = 6;
  public static final int Url = 75;
  public static final int Numeros = 45;
  public static final int Derecha = 67;
  public static final int Radio = 57;
  public static final int Columnas = 74;
  public static final int Indice = 62;
  public static final int Combo = 60;
  public static final int EXP_user_pass = 80;
  public static final int Justificar = 68;
  public static final int NuevoPassword = 29;
  public static final int ModificarComponente = 50;
  public static final int Requerido = 69;
  public static final int AreaTexto = 55;
  public static final int ModificarForm = 40;
  public static final int DirURL = 82;
  public static final int NombreCampo = 51;
  public static final int Alineacion = 64;
  public static final int Separador = 15;
  public static final int IniSolicitudes = 5;
  public static final int UserAntiguo = 24;
  public static final int Allids = 44;
  public static final int DipleR = 3;
  public static final int TextoVisible = 63;
  public static final int Centro = 65;
  public static final int DipleL = 2;
  public static final int EOF = 0;
  public static final int AgregarComponente = 48;
  public static final int UserNuevo = 25;
  public static final int Fichero = 58;
  public static final int UserCreacion = 37;
  public static final int NombreForm = 35;
  public static final int CampoTexto = 54;
  public static final int Login = 28;
  public static final int CredencialUser = 19;
  public static final int FechaCreacion = 38;
  public static final int TWhite = 43;
  public static final int error = 1;
  public static final int No = 71;
  public static final int FechaModif = 26;
  public static final int ID = 33;
  public static final int EliminarComponente = 49;
  public static final int Izquierda = 66;
  public static final int Filas = 73;
  public static final int ModificarUser = 23;
  public static final int TDark = 41;
  public static final int DatosRecopilados = 79;
  public static final int Letras = 46;
  public static final int Password = 22;
  public static final int IdFormulario = 77;
  public static final int Checkbox = 56;
  public static final int Textos = 81;
  public static final int Clase = 53;
  public static final int Si = 70;
  public static final int TBlue = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DipleL",
  "DipleR",
  "Exclamation",
  "IniSolicitudes",
  "FinSolicitudes",
  "IniSolicitud",
  "FinSolicitud",
  "Parentesis_L",
  "Parentesis_R",
  "Corchete_L",
  "Corchete_R",
  "Llave_L",
  "Llave_R",
  "Separador",
  "DosP",
  "Coma",
  "Comilla",
  "CredencialUser",
  "CrearUsuario",
  "Usuario",
  "Password",
  "ModificarUser",
  "UserAntiguo",
  "UserNuevo",
  "FechaModif",
  "EliminarUsuario",
  "Login",
  "NuevoPassword",
  "FechaF",
  "ParametroForm",
  "NuevoFormulario",
  "ID",
  "TituloForm",
  "NombreForm",
  "TemaForm",
  "UserCreacion",
  "FechaCreacion",
  "EliminarForm",
  "ModificarForm",
  "TDark",
  "TBlue",
  "TWhite",
  "Allids",
  "Numeros",
  "Letras",
  "ParametrosComponente",
  "AgregarComponente",
  "EliminarComponente",
  "ModificarComponente",
  "NombreCampo",
  "Formulario",
  "Clase",
  "CampoTexto",
  "AreaTexto",
  "Checkbox",
  "Radio",
  "Fichero",
  "Imagen",
  "Combo",
  "Boton",
  "Indice",
  "TextoVisible",
  "Alineacion",
  "Centro",
  "Izquierda",
  "Derecha",
  "Justificar",
  "Requerido",
  "Si",
  "No",
  "Opciones",
  "Filas",
  "Columnas",
  "Url",
  "InicioGuardaForm",
  "IdFormulario",
  "Estructura",
  "DatosRecopilados",
  "EXP_user_pass",
  "Textos",
  "DirURL"
  };
}

