
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorUsuario;

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;
import java.util.ArrayList;
import FormSolicitudIndigo.*;
import ComponentesIndigo.*;
import UsuarioIndigo.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parserU extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return parserUSym.class;
}

  /** Default constructor. */
  @Deprecated
  public parserU() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parserU(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserU(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\011\000\002\002\004\000\002\002\003\000\002\007" +
    "\007\000\002\007\005\000\002\017\002\000\002\020\002" +
    "\000\002\010\033\000\002\016\003\000\002\016\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\042\000\004\017\004\001\002\000\004\024\011\001" +
    "\002\000\004\002\007\001\002\000\004\002\000\001\002" +
    "\000\004\002\001\001\002\000\004\020\042\001\002\000" +
    "\004\027\012\001\002\000\004\024\013\001\002\000\004" +
    "\022\014\001\002\000\004\024\015\001\002\000\004\122" +
    "\016\001\002\000\004\024\017\001\002\000\004\023\020" +
    "\001\002\000\004\024\ufffd\001\002\000\004\024\022\001" +
    "\002\000\004\030\023\001\002\000\004\024\024\001\002" +
    "\000\004\022\025\001\002\000\004\024\026\001\002\000" +
    "\004\122\027\001\002\000\004\024\030\001\002\000\004" +
    "\023\031\001\002\000\004\024\ufffc\001\002\000\004\024" +
    "\033\001\002\000\004\050\034\001\002\000\004\024\035" +
    "\001\002\000\004\022\036\001\002\000\004\024\037\001" +
    "\002\000\004\040\040\001\002\000\004\024\041\001\002" +
    "\000\004\020\ufffb\001\002\000\006\002\ufffe\023\043\001" +
    "\002\000\004\017\004\001\002\000\004\002\uffff\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\042\000\006\002\004\007\005\001\001\000\004\010" +
    "\007\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\017\020\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\020\031\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\043\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserU$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserU$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserU$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


	
	Formulario formR= new Formulario();
	Componente compR= new Componente();
	public CrearUsuario objCrearUsuario= new CrearUsuario();
	ArrayList<Formulario> lstFormulario = new ArrayList<Formulario>();
	ArrayList<CrearUsuario> lst = new ArrayList<CrearUsuario>();
	ArrayList<Componente>  lstComponente = new ArrayList<Componente>();

	//constructor
	private Symbol sym;
    int contCreaUser=0;
    public Symbol getS(){
        return this.sym;
    }
	public parserU( LexerU lex){
	 super(lex);
	}
	public void report_error(String message, Object info){
		System.out.println("\nREPORT ERROR");
	}
	public void report_fatal_error(String message, Object info){
		System.out.println("\nREPORT FATAL");
	}
	
	public void syntax_error(Symbol cur_token) {
        System.out.println(symbl_name_from_id(expected_token_ids().get(0)));
        System.out.println("syntaxerr: " + symbl_name_from_id(cur_token.sym) +" Columna: "+cur_token.right+" Linea: "+cur_token.left+" Valor:"+cur_token.value);
    }
	protected int error_sync_size() {
        return 1;
    }
	public ArrayList<Formulario> getLstFormulario() {
        return lstFormulario;
    }
	public ArrayList<CrearUsuario> getUsuarios() {
        return lst;
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parserU$actions {
  private final parserU parser;

  /** Constructor */
  CUP$parserU$actions(parserU parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parserU$do_action_part00000000(
    int                        CUP$parserU$act_num,
    java_cup.runtime.lr_parser CUP$parserU$parser,
    java.util.Stack            CUP$parserU$stack,
    int                        CUP$parserU$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserU$result;

      /* select the action based on the action number */
      switch (CUP$parserU$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= ESTADO_INICIAL EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parserU$stack.elementAt(CUP$parserU$top-1)).value;
		RESULT = start_val;
              CUP$parserU$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-1)), ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserU$parser.done_parsing();
          return CUP$parserU$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // ESTADO_INICIAL ::= DB_Form 
            {
              Object RESULT =null;

              CUP$parserU$result = parser.getSymbolFactory().newSymbol("ESTADO_INICIAL",0, ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), RESULT);
            }
          return CUP$parserU$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // DB_Form ::= Llave_L BLOQUE_DB Llave_R Coma DB_Form 
            {
              Object RESULT =null;

              CUP$parserU$result = parser.getSymbolFactory().newSymbol("DB_Form",5, ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-4)), ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), RESULT);
            }
          return CUP$parserU$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // DB_Form ::= Llave_L BLOQUE_DB Llave_R 
            {
              Object RESULT =null;

              CUP$parserU$result = parser.getSymbolFactory().newSymbol("DB_Form",5, ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-2)), ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), RESULT);
            }
          return CUP$parserU$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$0 ::= 
            {
              Object RESULT =null;
		int aaleft = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-2)).left;
		int aaright = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-2)).right;
		Object aa = (Object)((java_cup.runtime.Symbol) CUP$parserU$stack.elementAt(CUP$parserU$top-2)).value;
objCrearUsuario.setUsuario(aa.toString());
              CUP$parserU$result = parser.getSymbolFactory().newSymbol("NT$0",13, ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), RESULT);
            }
          return CUP$parserU$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$1 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parserU$stack.elementAt(CUP$parserU$top-8)).value;
		int aaleft = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-11)).left;
		int aaright = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-11)).right;
		Object aa = (Object)((java_cup.runtime.Symbol) CUP$parserU$stack.elementAt(CUP$parserU$top-11)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$parserU$stack.elementAt(CUP$parserU$top-2)).value;
objCrearUsuario.setPassword(a.toString());
              CUP$parserU$result = parser.getSymbolFactory().newSymbol("NT$1",14, ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), RESULT);
            }
          return CUP$parserU$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // BLOQUE_DB ::= Comilla Usuario Comilla DosP Comilla EXP_user_pass Comilla Coma NT$0 Comilla Password Comilla DosP Comilla EXP_user_pass Comilla Coma NT$1 Comilla FechaCreacion Comilla DosP Comilla FechaF Comilla 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parserU$stack.elementAt(CUP$parserU$top-7)).value;
		int aaleft = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-20)).left;
		int aaright = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-20)).right;
		Object aa = (Object)((java_cup.runtime.Symbol) CUP$parserU$stack.elementAt(CUP$parserU$top-20)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-11)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-11)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$parserU$stack.elementAt(CUP$parserU$top-11)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-2)).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$parserU$stack.elementAt(CUP$parserU$top-2)).value;
		objCrearUsuario.setFechaCreacion(f.toString()); lst.add(objCrearUsuario);  objCrearUsuario= new CrearUsuario(); 
              CUP$parserU$result = parser.getSymbolFactory().newSymbol("BLOQUE_DB",6, ((java_cup.runtime.Symbol)CUP$parserU$stack.elementAt(CUP$parserU$top-24)), ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), RESULT);
            }
          return CUP$parserU$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // TEXTOS ::= Textos 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parserU$stack.peek()).value;
		 RESULT=t;
              CUP$parserU$result = parser.getSymbolFactory().newSymbol("TEXTOS",12, ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), RESULT);
            }
          return CUP$parserU$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // TEXTOS ::= EXP_user_pass 
            {
              Object RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()).left;
		int wright = ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()).right;
		Object w = (Object)((java_cup.runtime.Symbol) CUP$parserU$stack.peek()).value;
		 RESULT=w;
              CUP$parserU$result = parser.getSymbolFactory().newSymbol("TEXTOS",12, ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserU$stack.peek()), RESULT);
            }
          return CUP$parserU$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parserU$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parserU$do_action(
    int                        CUP$parserU$act_num,
    java_cup.runtime.lr_parser CUP$parserU$parser,
    java.util.Stack            CUP$parserU$stack,
    int                        CUP$parserU$top)
    throws java.lang.Exception
    {
              return CUP$parserU$do_action_part00000000(
                               CUP$parserU$act_num,
                               CUP$parserU$parser,
                               CUP$parserU$stack,
                               CUP$parserU$top);
    }
}

}
